name: Java CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "All External"
            kafka-bootstrap-servers: "172.28.11.1:9092"
            kafka-connect-host: "http://172.28.11.11:8083"
          - name: "Standalone w/ ext Kafka"
            kafka-bootstrap-servers: "172.28.11.1:9092"
          - name: "All Internal"

    name: ${{ matrix.name }}

    steps:
      - name: Start Kafka
        run: ./docker/start_kafka.sh
      - name: Start Database
        run: ./docker/start_db.sh
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Test
        run: mvn test -Dkafka.bootstrap.servers=${{matrix.kafka-bootstrap-servers}} -Dkafka.connect.host=${{matrix.kafka-connect-host}}
